version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    reviewers:
      - rabotaua/backend
      - rabotaua/frontend
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
    reviewers:
      - rabotaua/backend
      - rabotaua/frontend
    groups:
      devDependencies:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "globals"
          - "husky"
          - "lint-staged"
          - "parcel"
          - "prettier"
          - "ts-*"
          - "typescript"
      dependencies:
        patterns:
          - "@actions/*"
