version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "Europe/Kiev"
    reviewers:
      - mac2000
      - rabotaua/leads
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "Europe/Kiev"
    reviewers:
      - mac2000
      - rabotaua/leads
